# Autogenerated by Astropy-affiliated package nuskybgd's setup.py on 2022-01-11 00:48:35 UTC
import datetime

version = "0.1"
githash = "9a0972c15b341d3dc476b7d4f03a859d5e55955a"


major = 0
minor = 1
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2022, 1, 11, 0, 48, 35)
debug = False

astropy_helpers_version = "4.1.dev1227"
